name: pantheon
channels:
  - bioconda
  - conda-forge
  - defaults
  - epi2melabs
dependencies:
  - python<=3.10
  - pysam
  - nextflow
  - pip
  - biopython
  - flye
  - megahit
  - pip:
      - git+https://github.com/rmcolq/aplanat_custom.git
